print('*'*30)
print('Bool(234) to:',bool(1))
print('Bool(0) to:',bool(0))
print('Bool('') to:',bool(''))
print('Bool([2]) to:',bool([2]))
print('Bool([]) to:',bool([]))
print('Bool({}) to:',bool({}))
print('Bool({4}) to:',bool({4}))
print('Każdy pusty str "", lista[], set{}, dict{:} jest:',bool(''),bool([]),bool({}) )
print('*'*30)